### ISSUE TITLE
1.1 compatability

### ISSUE THREAD

**Issue by Sureiya** [Bouhm/StardewValleyMods#1]
I've attempted to fix this myself, but haven't had any luck.

`[08:37:27.669 PM] An exception occured in XNA UpdateTick: System.MissingFieldException: Field not found: 'StardewValley.Game1.content'.
   at NPCMapLocations.MapPageTooltips..ctor(String names, Int32 nameTooltipMode)
   at NPCMapLocations.MapModMain.GameEvents_UpdateTick(Object sender, EventArgs e)
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at StardewModdingAPI.Events.GameEvents.InvokeUpdateTick()`

**Comment by k0d3k1ttn** [comment]
+1  I love this mod -- so much that I'm hesitant to start a new 1.1 save like I was planning to now that I see it isn't working.  Hoping for a fix soon! <3

**Comment by Bouhm** [comment]
Thanks for letting me know! Should be working fine now.

**Comment by k0d3k1ttn** [comment]
Yay!! I'll check it out tomorrow and get back if I have any more issues!
Thanks for fixing it so quickly!
